version: '3'

services:
    bot:
        container_name: bot
        build:
            context: ./bot
            dockerfile: Dockerfile
        restart: always
        environment:
            MONGO_DB: mongodb://root:pass_4_db_secret321@195.133.25.151:27017
            BOT_TOKEN: 6689643880:AAHUunBjAx944sKOb_gE7oRl_O0pHfsux1w
        volumes:
            # - ./bot/file:/usr/src/tg_sber_bot/file
            - ./bot/logs.log:/usr/src/tg_sber_bot/logs.log
        depends_on:
            - mongo

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./mongo-data:/data/db
            - ./backup:/backup/
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass_4_db_secret321
